### PR TITLE
feat: add py35 support

### PR DESCRIPTION
**Pull request by munagekar**
Please consider supporting python 3.5.  I have made the following changes

- Fixed Lint
- Replaced f-strings with format strings for py 3.5
- Replaced enum.auto with actual number for py 3.5
- Updated the variable annotations for py 3.5.
- Added a standard gitignore
- Update setup.cfg for python 3.5.

I have ran the test suite on python 3.5.9 as well as python 3.8.2. It works on both.

### CODE REVIEW

**Comment by rr-** [comment]
-1 for importing directly from `typing`
-1 for adding bloated .gitignore
-1 for weird indentation that is not compatible with black

Why do you need Python 3.5?

**Comment by munagekar** [comment]
Thank you for the quick review.

> -1 for importing directly from typing thus polluting global namespace with myriad of inconsistent generic names

I'll revert this

> -1 for adding bloated .gitignore

I'll revert this

> - 1 for weird indentation that is not compatible with black

I'll format files with black and fix indentation.

> Why do you need Python 3.5?

I am trying to add this as a [dependency for kubeflow/pipelines](https://github.com/kubeflow/pipelines/pull/4512).

**Comment by munagekar** [comment]
@rr- Thank you for the quick review.

> -1 for importing directly from typing thus polluting global namespace with myriad of inconsistent generic names

I'll revert this

> -1 for adding bloated .gitignore

I'll revert this

> - 1 for weird indentation that is not compatible with black

I'll format files with black and fix indentation.

> Why do you need Python 3.5?

I am trying to add this as a [dependency for kubeflow/pipelines](https://github.com/kubeflow/pipelines/pull/4512).

**Review by rr- — APPROVED** [review]

**Comment by rr-** [comment]
released as 0.7.3; thanks

**Pull request merged**
